### ISSUE TITLE
location没有path属性，应该是pathname

### ISSUE THREAD

**Issue by luyilin** [k-dylan/SRouter#1]
SRouter/src/SRouter.js:68
应该改为var path = location.pathname;，否则pushState方式下会报错

另外SRouter/src/SRouter.js:19

```
this.mode = options && options.mode == 'history'
                        &&  !!(history.pushState) ? 'hash' : 'history';
```

这个判断好像有问题，请review一下哈

**Comment by k-dylan** [comment]
感谢提醒！ loaction.path 这里确实是写错了！ 
不过 SRouter/src/SRouter.js:19 我刚检查过了，应该没有问题
